name: 'Validate Release PR'
description: 'Performs checks on release PRs'
author: 'EdgeDB Inc.'
inputs:
  github_token:
    description: Github API token.
    required: true
  version_file:
    description: Path to the file contaning the version string.
    required: false
  version_expr:
    description: |
      Extended regular expression used to match the line with the
      version string.  The first capturing group must match the
      version string itself, excluding the quotes.  The pattern may
      contain [[:PEP440:]] and [[:SEMVER:]] magic "classes" that match
      Python and SemVer versions correspondingly.
    default: ''
    required: false
outputs:
  version:
    description: The release version.
  approved:
    description: Whether the PR is approved.
runs:
  using: 'docker'
  image: 'Dockerfile'
