name: 'Validate Release PR'
description: 'Performs checks on release PRs'
author: 'EdgeDB Inc.'
inputs:
  github_token:
    description: Github API token.
  version_file:
    description: Path to the file containing the version string.
    required: true
  version_line_pattern:
    description: |
      Extended regular expression used to match the line with the
      version string.  The first capturing group must match the
      version string itself, excluding the quotes.  The pattern may
      contain [[:PEP440:]] and [[:SEMVER:]] magic "classes" that match
      Python and SemVer versions correspondingly.
    required: true
  missing_version_ok:
    description: |
      Whether the absence of a version change in the PR diff is considered
      an error.
    default: 'no'
  require_approval:
    description: |
      Whether an explicit approval from another maintainer is required.
    default: 'yes'
  require_team:
    description: |
      Require membership in the specified team.
  require_access_level:
    description: |
      Require a specific repository access level for the team that the
      PR submitter is a member of.  Applies to *require_team*, if specified,
      otherwise membership in any team with adequate access is sufficient.
    default: MAINTAIN
outputs:
  version:
    description: The release version.
  approved:
    description: Whether the PR is approved.
runs:
  using: 'node20'
  main: 'dist/index.cjs'
branding:
  icon: 'tag'
  color: 'gray-dark'
